// Generated by BUCKLESCRIPT VERSION 1.9.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact       = require("reason-react/src/reasonReact.js");
var ReactHelmet       = require("react-helmet");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");

function make(title, meta, children) {
  return ReasonReact.wrapJsForReason(ReactHelmet.default, {
              title: Js_null_undefined.from_opt(title),
              meta: Js_null_undefined.from_opt(meta)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
