// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var Helpers     = require("../utils/Helpers.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Package");

function make(data, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", undefined, React.createElement("h1", undefined, Helpers.text(data.packagesJson.name)), React.createElement("span", undefined, Helpers.text("(" + (data.packagesJson.version + ")"))), React.createElement("div", undefined, Helpers.text(data.packagesJson.description)), React.createElement("div", {
                      dangerouslySetInnerHTML: {
                        __html: data.packagesJson.fields.html
                      }
                    }));
    });
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.data, /* array */[]);
      }));


  export const query = graphql`
    query PackageQuery($slug: String = "bs-json") {
      packagesJson(fields: { slug: { eq: $slug }}) {
        name
        version
        description

        fields {
          html
        }
      }
    }
  `

;

exports.component = component;
exports.make      = make;
exports.$$default = $$default;
exports.default   = $$default;
exports.__esModule= true;
/* component Not a pure module */
