// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Tag           = require("../components/Tag.js");
var Icon          = require("../bindings/Icon.js");
var Link          = require("../bindings/gatsby/link.js");
var React         = require("react");
var Control       = require("../components/helpers/Control.js");
var Helpers       = require("../utils/Helpers.js");
var TimeAgo       = require("../bindings/TimeAgo.js");
var ReasonReact   = require("reason-react/src/ReasonReact.js");
var Js_primitive  = require("bs-platform/lib/js/js_primitive.js");
var PackageStyles = require("../styles/PackageStyles.js");

var component = ReasonReact.statelessComponent("Package");

function make(data, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var $$package = data.package;
      var match = $$package.license;
      var match$1 = $$package.type;
      var tmp = match$1 === "unpublished" ? React.createElement("span", {
              className: PackageStyles.unpublishedLabel
            }, Helpers.text("unpublished")) : null;
      var tmp$1 = { };
      var tmp$2 = Js_primitive.null_undefined_to_opt($$package.homepageUrl);
      if (tmp$2) {
        tmp$1.href = tmp$2[0];
      }
      var tmp$3 = { };
      var tmp$4 = Js_primitive.null_undefined_to_opt($$package.repositoryUrl);
      if (tmp$4) {
        tmp$3.href = tmp$4[0];
      }
      var tmp$5 = { };
      var tmp$6 = Js_primitive.null_undefined_to_opt($$package.npmUrl);
      if (tmp$6) {
        tmp$5.href = tmp$6[0];
      }
      var tmp$7 = { };
      var tmp$8 = Js_primitive.null_undefined_to_opt($$package.issuesUrl);
      if (tmp$8) {
        tmp$7.href = tmp$8[0];
      }
      var tmp$9 = { };
      var tmp$10 = Js_primitive.null_undefined_to_opt($$package.docsUrl);
      if (tmp$10) {
        tmp$9.href = tmp$10[0];
      }
      return React.createElement("div", undefined, React.createElement("header", {
                      className: PackageStyles.header($$package.type)
                    }, React.createElement("div", {
                          className: PackageStyles.props
                        }, ReasonReact.element(/* None */0, /* None */0, Control.IfSome[/* make */1](Js_primitive.null_undefined_to_opt($$package.stars), (function (stars) {
                                    return React.createElement("div", {
                                                className: PackageStyles.stars
                                              }, Helpers.text(stars), ReasonReact.element(/* None */0, /* None */0, Icon.Star[/* make */0](/* Some */[PackageStyles.starIcon], /* array */[])));
                                  }))), (match == null) ? React.createElement("div", {
                                className: PackageStyles.nolicense
                              }, Helpers.text("No license")) : React.createElement("div", {
                                className: PackageStyles.license
                              }, Helpers.text(match)), React.createElement("div", {
                              className: PackageStyles.updated
                            }, ReasonReact.element(/* None */0, /* None */0, TimeAgo.make($$package.updated, /* array */[])))), React.createElement("div", {
                          className: PackageStyles.title
                        }, ReasonReact.element(/* None */0, /* None */0, Link.make($$package.slug, /* Some */[PackageStyles.name], /* None */0, /* array */[Helpers.text($$package.name)])), React.createElement("span", {
                              className: PackageStyles.version
                            }, Helpers.text($$package.version)), tmp), React.createElement("div", {
                          className: PackageStyles.fields
                        }, React.createElement("div", {
                              className: PackageStyles.description
                            }, Helpers.text($$package.description)), React.createElement("div", {
                              className: PackageStyles.tags
                            }, ReasonReact.element(/* None */0, /* None */0, Icon.Tags[/* make */0](/* Some */[PackageStyles.tagsIcon], /* array */[])), ReasonReact.element(/* None */0, /* None */0, Control.$$Map[/* make */1]($$package.keywords, /* Some */[Helpers.text(" - ")], (function (keyword) {
                                        return ReasonReact.element(/* Some */[keyword], /* None */0, Tag.make(keyword, /* array */[]));
                                      }))))), React.createElement("div", {
                          className: PackageStyles.links
                        }, React.createElement("a", tmp$1, Helpers.text("homepage")), React.createElement("a", tmp$3, Helpers.text("repository")), React.createElement("a", tmp$5, Helpers.text("npm")), React.createElement("a", tmp$7, Helpers.text("issues")), React.createElement("a", tmp$9, Helpers.text("documentation")))), React.createElement("div", {
                      className: PackageStyles.readme,
                      dangerouslySetInnerHTML: {
                        __html: $$package.readme
                      }
                    }));
    });
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.data, /* array */[]);
      }));


  export const query = graphql`
    query PackageQuery($id: String!) {
      package: packages(id: { eq: $id }) {
        type
        id
        name
        version
        description
        keywords
        license
        updated
        stars
        readme
        homepageUrl
        repositoryUrl
        npmUrl
        issuesUrl

        slug
      }
    }
  `

;

var Styles = 0;

exports.Styles    = Styles;
exports.component = component;
exports.make      = make;
exports.$$default = $$default;
exports.default   = $$default;
exports.__esModule= true;
/* component Not a pure module */
