// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array     = require("bs-platform/lib/js/array.js");
var Curry       = require("bs-platform/lib/js/curry.js");
var Fragment    = require("../../bindings/react/Fragment.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Control.Map");

function make(items, $staropt$star, render) {
  var empty = $staropt$star ? $staropt$star[0] : null;
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, Fragment.make(/* array */[items.length !== 0 ? $$Array.map(render, items) : empty]));
    });
  return newrecord;
}

var $$Map = /* module */[
  /* component */component,
  /* make */make
];

var component$1 = ReasonReact.statelessComponent("Control.IfSome");

function make$1(option, render) {
  var newrecord = component$1.slice();
  newrecord[/* render */9] = (function () {
      if (option) {
        return Curry._1(render, option[0]);
      } else {
        return null;
      }
    });
  return newrecord;
}

var IfSome = /* module */[
  /* component */component$1,
  /* make */make$1
];

exports.$$Map  = $$Map;
exports.IfSome = IfSome;
/* component Not a pure module */
