// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Css          = require("bs-css/src/Css.js");
var Theme        = require("./Theme.js");
var GlobalStyles = require("./GlobalStyles.js");

var widthContainer = Css.style(/* :: */[
      Css.unsafe("label", "width-container"),
      /* :: */[
        Css.unsafe("margin", "0 auto"),
        /* :: */[
          Css.maxWidth(Css.px(960)),
          /* :: */[
            Css.minWidth(Css.px(359)),
            /* :: */[
              Css.width(Css.pct(100)),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var html = Css.style(/* :: */[
      Css.selector("& h1", /* :: */[
            Css.fontSize(Css.rem(2.25)),
            /* :: */[
              Css.fontWeight(/* Bold */1),
              /* :: */[
                Css.lineHeight(Css.em(1.1)),
                /* :: */[
                  Css.marginBottom(Css.rem(1.45)),
                  /* [] */0
                ]
              ]
            ]
          ]),
      /* :: */[
        Css.selector("& h2", /* :: */[
              Css.fontSize(Css.rem(1.62671)),
              /* :: */[
                Css.fontWeight(/* Bold */1),
                /* :: */[
                  Css.lineHeight(Css.em(1.1)),
                  /* :: */[
                    Css.marginBottom(Css.rem(1.45)),
                    /* [] */0
                  ]
                ]
              ]
            ]),
        /* :: */[
          Css.selector("& h3", /* :: */[
                Css.fontSize(Css.rem(1.38316)),
                /* :: */[
                  Css.fontWeight(/* Bold */1),
                  /* :: */[
                    Css.lineHeight(Css.em(1.1)),
                    /* :: */[
                      Css.marginBottom(Css.rem(1.45)),
                      /* [] */0
                    ]
                  ]
                ]
              ]),
          /* :: */[
            Css.selector("& h1, & h2, & h3, & h4, & h5", /* :: */[
                  Css.selector("& > a.anchor", /* :: */[
                        Css.marginLeft(Css.px(-20)),
                        /* :: */[
                          Css.paddingRight(Css.px(4)),
                          /* :: */[
                            Css.selector("& > svg", /* :: */[
                                  Css.visibility(/* Hidden */1),
                                  /* [] */0
                                ]),
                            /* [] */0
                          ]
                        ]
                      ]),
                  /* :: */[
                    Css.hover(/* :: */[
                          Css.selector("& > a.anchor > svg", /* :: */[
                                Css.visibility(/* Visible */0),
                                /* [] */0
                              ]),
                          /* [] */0
                        ]),
                    /* [] */0
                  ]
                ]),
            /* :: */[
              Css.selector("& p", /* :: */[
                    Css.marginBottom(Css.rem(1.45)),
                    /* :: */[
                      Css.selector("& *:last-child", /* :: */[
                            Css.marginBottom(Css.zero),
                            /* [] */0
                          ]),
                      /* [] */0
                    ]
                  ]),
              /* :: */[
                Css.selector("& b, & strong", /* :: */[
                      Css.fontWeight(/* Bold */1),
                      /* [] */0
                    ]),
                /* :: */[
                  Css.selector("& i, & em", /* :: */[
                        Css.fontStyle(/* Italic */1),
                        /* [] */0
                      ]),
                  /* :: */[
                    Css.selector("& ol, & ul", /* :: */[
                          Css.margin(Css.zero),
                          /* :: */[
                            Css.marginLeft(Css.rem(1.45)),
                            /* :: */[
                              Css.marginBottom(Css.rem(1.45)),
                              /* :: */[
                                Css.unsafe("listStylePosition", "outside"),
                                /* :: */[
                                  Css.unsafe("listStyleImage", "none"),
                                  /* [] */0
                                ]
                              ]
                            ]
                          ]
                        ]),
                    /* :: */[
                      Css.selector("& li", /* :: */[
                            Css.marginBottom(Css.rem(1.45 / 2)),
                            /* :: */[
                              Css.selector("& > ol, & > ul", /* :: */[
                                    Css.marginLeft(Css.rem(1.45)),
                                    /* :: */[
                                      Css.marginBottom(Css.rem(1.45 / 2)),
                                      /* :: */[
                                        Css.marginTop(Css.rem(1.45 / 2)),
                                        /* [] */0
                                      ]
                                    ]
                                  ]),
                              /* :: */[
                                Css.selector("& *:last-child", /* :: */[
                                      Css.marginBottom(Css.zero),
                                      /* [] */0
                                    ]),
                                /* :: */[
                                  Css.selector("& > p", /* :: */[
                                        Css.marginBottom(Css.rem(1.45 / 2)),
                                        /* [] */0
                                      ]),
                                  /* [] */0
                                ]
                              ]
                            ]
                          ]),
                      /* :: */[
                        Css.selector("& ol", /* :: */[
                              Css.unsafe("listStyleType", "decimal"),
                              /* :: */[
                                Css.selector("& li", /* :: */[
                                      Css.paddingLeft(Css.zero),
                                      /* [] */0
                                    ]),
                                /* [] */0
                              ]
                            ]),
                        /* :: */[
                          Css.selector("& ul", /* :: */[
                                Css.unsafe("listStyleType", "disc"),
                                /* :: */[
                                  Css.selector("& li", /* :: */[
                                        Css.paddingLeft(Css.zero),
                                        /* [] */0
                                      ]),
                                  /* [] */0
                                ]
                              ]),
                          /* :: */[
                            Css.selector("& code", /* :: */[
                                  Css.unsafe("background", "hsla(0, 0%, 0%, 0.04)"),
                                  /* :: */[
                                    Css.fontFamily("'SFMono-Regular', Consolas, 'Roboto Mono', 'Droid Sans Mono', 'Liberation Mono', Menlo, Courier, monospace"),
                                    /* :: */[
                                      Css.fontSize(Css.rem(0.85)),
                                      /* :: */[
                                        Css.lineHeight(Css.rem(1.45)),
                                        /* :: */[
                                          Css.unsafe("padding", ".2em 0"),
                                          /* [] */0
                                        ]
                                      ]
                                    ]
                                  ]
                                ]),
                            /* :: */[
                              Css.selector("& pre", /* :: */[
                                    Css.marginBottom(Css.rem(1.45)),
                                    /* :: */[
                                      Css.fontSize(Css.rem(0.85)),
                                      /* :: */[
                                        Css.lineHeight(Css.rem(1.42)),
                                        /* :: */[
                                          Css.unsafe("background", "hsla(0, 0%, 0%, 0.04)"),
                                          /* :: */[
                                            Css.overflow(/* Auto */3),
                                            /* :: */[
                                              Css.unsafe("wordWrap", "normal"),
                                              /* :: */[
                                                Css.padding(Css.rem(1.45)),
                                                /* :: */[
                                                  Css.selector("& code", /* :: */[
                                                        Css.background(/* None */0),
                                                        /* :: */[
                                                          Css.lineHeight(Css.em(1.42)),
                                                          /* [] */0
                                                        ]
                                                      ]),
                                                  /* [] */0
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]),
                              /* :: */[
                                Css.selector("& a", /* :: */[
                                      Css.color(Theme.Color[/* link */5]),
                                      /* :: */[
                                        Css.textDecorationLine(/* None */0),
                                        /* :: */[
                                          Css.selector("&:hover", /* :: */[
                                                Css.textDecorationLine(/* Values */[/* :: */[
                                                        /* Underline */0,
                                                        /* [] */0
                                                      ]]),
                                                /* [] */0
                                              ]),
                                          /* [] */0
                                        ]
                                      ]
                                    ]),
                                /* :: */[
                                  Css.selector("& img", /* :: */[
                                        Css.maxWidth(Css.pct(100)),
                                        /* [] */0
                                      ]),
                                  /* :: */[
                                    Css.selector("& .redex-codeblock.m-tabbed", /* :: */[
                                          Css.display(/* Flex */3),
                                          /* :: */[
                                            Css.position(/* Relative */1),
                                            /* :: */[
                                              Css.selector("& > ul", /* :: */[
                                                    Css.display(/* Flex */3),
                                                    /* :: */[
                                                      Css.position(/* Absolute */2),
                                                      /* :: */[
                                                        Css.flexDirection(/* Column */2),
                                                        /* :: */[
                                                          Css.margin(Css.zero),
                                                          /* :: */[
                                                            Css.opacity(0),
                                                            /* :: */[
                                                              Css.transition(/* Some */[200], /* Some */[400], /* None */0, "opacity"),
                                                              /* :: */[
                                                                Css.transform(Css.translateX(Css.pct(-100))),
                                                                /* :: */[
                                                                  Css.height(Css.pct(100)),
                                                                  /* :: */[
                                                                    Css.selector("& > li", /* :: */[
                                                                          Css.cursor(/* Pointer */5),
                                                                          /* :: */[
                                                                            Css.margin(Css.zero),
                                                                            /* :: */[
                                                                              Css.display(/* InlineBlock */11),
                                                                              /* :: */[
                                                                                Css.padding2(Css.em(0.35), Css.em(0.75)),
                                                                                /* :: */[
                                                                                  Css.color(Css.white),
                                                                                  /* :: */[
                                                                                    Css.textTransform(/* Lowercase */2),
                                                                                    /* :: */[
                                                                                      Css.fontVariant(/* SmallCaps */1),
                                                                                      /* :: */[
                                                                                        Css.selector("&:not(.s-selected)", /* :: */[
                                                                                              Css.opacity(0.5),
                                                                                              /* :: */[
                                                                                                Css.unsafe("boxShadow", "inset 0 -4px 2px -2px rgba(0, 0, 0, 0.1)"),
                                                                                                /* :: */[
                                                                                                  Css.hover(/* :: */[
                                                                                                        Css.opacity(1),
                                                                                                        /* [] */0
                                                                                                      ]),
                                                                                                  /* [] */0
                                                                                                ]
                                                                                              ]
                                                                                            ]),
                                                                                        /* :: */[
                                                                                          Css.selector("&.reason", /* :: */[
                                                                                                Css.backgroundColor(Theme.Color[/* reason */8]),
                                                                                                /* [] */0
                                                                                              ]),
                                                                                          /* :: */[
                                                                                            Css.selector("&.ml", /* :: */[
                                                                                                  Css.backgroundColor(Theme.Color[/* ocaml */9]),
                                                                                                  /* [] */0
                                                                                                ]),
                                                                                            /* [] */0
                                                                                          ]
                                                                                        ]
                                                                                      ]
                                                                                    ]
                                                                                  ]
                                                                                ]
                                                                              ]
                                                                            ]
                                                                          ]
                                                                        ]),
                                                                    /* [] */0
                                                                  ]
                                                                ]
                                                              ]
                                                            ]
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ]),
                                              /* :: */[
                                                Css.hover(/* :: */[
                                                      Css.selector("& > ul", /* :: */[
                                                            Css.opacity(1),
                                                            /* [] */0
                                                          ]),
                                                      /* [] */0
                                                    ]),
                                                /* :: */[
                                                  Css.selector("& > .codeblock", /* :: */[
                                                        Css.display(/* None */1),
                                                        /* :: */[
                                                          Css.flex(1),
                                                          /* :: */[
                                                            Css.maxWidth(Css.pct(100)),
                                                            /* :: */[
                                                              Css.selector("&.s-selected", /* :: */[
                                                                    Css.display(/* Block */0),
                                                                    /* [] */0
                                                                  ]),
                                                              /* :: */[
                                                                Css.selector("& > pre", /* :: */[
                                                                      Css.marginTop(Css.zero),
                                                                      /* :: */[
                                                                        Css.selector("&.lang-reason", /* :: */[
                                                                              Css.borderLeft(Css.px(2), /* Solid */2, Theme.Color[/* reason */8]),
                                                                              /* [] */0
                                                                            ]),
                                                                        /* :: */[
                                                                          Css.selector("&.lang-ml", /* :: */[
                                                                                Css.borderLeft(Css.px(2), /* Solid */2, Theme.Color[/* ocaml */9]),
                                                                                /* [] */0
                                                                              ]),
                                                                          /* [] */0
                                                                        ]
                                                                      ]
                                                                    ]),
                                                                /* [] */0
                                                              ]
                                                            ]
                                                          ]
                                                        ]
                                                      ]),
                                                  /* [] */0
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]),
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var _reset = GlobalStyles._reset;

var _global = GlobalStyles._global;

exports._reset         = _reset;
exports._global        = _global;
exports.widthContainer = widthContainer;
exports.html           = html;
/* widthContainer Not a pure module */
