// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");

var widthContainer = Css.style(/* :: */[
      Css.unsafe("margin", "0 auto"),
      /* :: */[
        Css.maxWidth(Css.px(960)),
        /* :: */[
          Css.width(Css.pct(100)),
          /* :: */[
            Css.unsafe("padding", "1.0875rem 1.45rem"),
            /* [] */0
          ]
        ]
      ]
    ]);

exports.widthContainer = widthContainer;
/* widthContainer Not a pure module */
