// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block  = require("bs-platform/lib/js/block.js");
var Glamor = require("bs-glamor/src/glamor.js");

require('./reset.css')
;

require('./global.css')
;

var root = Glamor.css(/* [] */0);

var header = Glamor.css(/* [] */0);

var widthContainer = Glamor.css(/* :: */[
      Glamor.margin("0 auto"),
      /* :: */[
        Glamor.maxWidth("960px"),
        /* :: */[
          Glamor.padding("1.0875rem 1.45rem"),
          /* [] */0
        ]
      ]
    ]);

var title = Glamor.css(/* :: */[
      Glamor.margin("0"),
      /* :: */[
        /* Selector */Block.__(1, [
            "& > a",
            /* :: */[
              Glamor.color("#DD4C39"),
              /* :: */[
                Glamor.textDecoration("none"),
                /* [] */0
              ]
            ]
          ]),
        /* [] */0
      ]
    ]);

var Layout = /* module */[
  /* root */root,
  /* header */header,
  /* widthContainer */widthContainer,
  /* title */title
];

var links = Glamor.css(/* :: */[
      Glamor.textAlign("center"),
      /* :: */[
        /* Selector */Block.__(1, [
            "& > a",
            /* :: */[
              Glamor.color("#DD4C39"),
              /* :: */[
                Glamor.fontSize(".85rem"),
                /* :: */[
                  Glamor.textDecoration("none"),
                  /* :: */[
                    Glamor.opacity(".5"),
                    /* :: */[
                      Glamor.margin("0 1em"),
                      /* :: */[
                        /* Selector */Block.__(1, [
                            "&:hover",
                            /* :: */[
                              Glamor.opacity("1"),
                              /* [] */0
                            ]
                          ]),
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]),
        /* [] */0
      ]
    ]);

var Index = /* module */[/* links */links];

exports.Layout = Layout;
exports.Index  = Index;
/*  Not a pure module */
