// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Css   = require("bs-css/src/Css.js");
var Theme = require("./Theme.js");

require('glamor-reset')
;

Css.$$global("*", /* :: */[
      Css.boxSizing(/* BorderBox */0),
      /* [] */0
    ]);

Css.$$global("*:focus", /* :: */[
      Css.outlineStyle(/* None */0),
      /* [] */0
    ]);

Css.$$global("body", /* :: */[
      Css.unsafe("lineHeight", "inherit"),
      /* :: */[
        Css.color(Theme.Color[/* text */3]),
        /* [] */0
      ]
    ]);

Css.$$global("h1, h2, h3", /* :: */[
      Css.lineHeight(Css.em(1.1)),
      /* :: */[
        Css.fontWeight(/* Normal */0),
        /* [] */0
      ]
    ]);

Css.$$global("a", /* :: */[
      Css.unsafe("color", "inherit"),
      /* [] */0
    ]);

Css.$$global("button, input, select", /* :: */[
      Css.unsafe("background", "none"),
      /* :: */[
        Css.unsafe("border", "none"),
        /* :: */[
          Css.unsafe("font", "inherit"),
          /* [] */0
        ]
      ]
    ]);

var _reset = Css.$$global("ol, ul", /* :: */[
      Css.unsafe("listStyle", "none"),
      /* :: */[
        Css.margin(Css.zero),
        /* :: */[
          Css.padding(Css.zero),
          /* [] */0
        ]
      ]
    ]);

Css.$$global("html", /* :: */[
      Css.fontSize(Css.px(15)),
      /* :: */[
        Css.lineHeight(Css.em(1.25)),
        /* :: */[
          Css.fontFamily("-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif"),
          /* :: */[
            Css.boxSizing(/* BorderBox */0),
            /* :: */[
              Css.overflowY(/* Scroll */2),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var _global = Css.$$global("html, body, #___gatsby", /* :: */[
      Css.backgroundColor(Theme.Color[/* background */2]),
      /* :: */[
        Css.minHeight(Css.pct(100)),
        /* [] */0
      ]
    ]);

var keywords = Css.style(/* :: */[
      Css.textAlign(/* Center */3),
      /* :: */[
        Css.marginTop(Css.em(3)),
        /* :: */[
          Css.lineHeight(Css.em(1.5)),
          /* :: */[
            Css.selector("& > a", /* :: */[
                  Css.display(/* InlineBlock */11),
                  /* :: */[
                    Css.unsafe("textDecoration", "none"),
                    /* :: */[
                      Css.unsafe("margin", "0 1ex"),
                      /* :: */[
                        Css.unsafe("whiteSpace", "nowrap"),
                        /* :: */[
                          Css.selector("& > .count", /* :: */[
                                Css.unsafe("marginLeft", ".5ex"),
                                /* :: */[
                                  Css.opacity(0.5),
                                  /* [] */0
                                ]
                              ]),
                          /* :: */[
                            Css.selector("&:hover > .label", /* :: */[
                                  Css.unsafe("textDecoration", "underline"),
                                  /* [] */0
                                ]),
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ]
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

var links = Css.style(/* :: */[
      Css.textAlign(/* Center */3),
      /* :: */[
        Css.selector("& > a", /* :: */[
              Css.fontSize(Css.rem(0.85)),
              /* :: */[
                Css.textDecoration(/* None */0),
                /* :: */[
                  Css.unsafe("margin", "0 1em"),
                  /* :: */[
                    Css.selector("&:hover", /* :: */[
                          Css.opacity(0.75),
                          /* [] */0
                        ]),
                    /* [] */0
                  ]
                ]
              ]
            ]),
        /* [] */0
      ]
    ]);

var lists = Css.style(/* :: */[
      Css.display(/* Flex */3),
      /* :: */[
        Css.justifyContent(/* SpaceAround */4),
        /* :: */[
          Css.marginTop(Css.em(3)),
          /* :: */[
            Css.selector("& > *", /* :: */[
                  Css.unsafe("padding", "0 1em"),
                  /* :: */[
                    Css.width(Css.pct(40)),
                    /* :: */[
                      Css.minWidth(Css.px(300)),
                      /* :: */[
                        Css.selector("& > h2", /* :: */[
                              Css.textAlign(/* Center */3),
                              /* :: */[
                                Css.fontSize(Css.em(1.1)),
                                /* :: */[
                                  Css.fontWeight(/* Bold */1),
                                  /* :: */[
                                    Css.unsafe("margin", ".5em 0"),
                                    /* :: */[
                                      Css.textTransform(/* Lowercase */2),
                                      /* :: */[
                                        Css.unsafe("fontVariant", "small-caps"),
                                        /* :: */[
                                          Css.paddingBottom(Css.em(0.5)),
                                          /* :: */[
                                            Css.borderBottom(Css.px(1), /* Solid */2, Css.rgba(255, 255, 255, 0.5)),
                                            /* [] */0
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]),
                        /* :: */[
                          Css.selector("& > div", /* :: */[
                                Css.background(/* None */0),
                                /* :: */[
                                  Css.unsafe("border", "none"),
                                  /* :: */[
                                    Css.padding(Css.zero),
                                    /* [] */0
                                  ]
                                ]
                              ]),
                          /* [] */0
                        ]
                      ]
                    ]
                  ]
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

var root = Css.style(/* :: */[
      Css.display(/* Flex */3),
      /* :: */[
        Css.justifyContent(/* SpaceBetween */5),
        /* :: */[
          Css.marginBottom(Css.em(0.5)),
          /* [] */0
        ]
      ]
    ]);

var name = Css.style(/* :: */[
      Css.textDecoration(/* None */0),
      /* :: */[
        Css.selector("&:hover", /* :: */[
              Css.unsafe("textDecoration", "underline"),
              /* [] */0
            ]),
        /* [] */0
      ]
    ]);

var version = Css.style(/* :: */[
      Css.fontSize(Css.em(0.85)),
      /* :: */[
        Css.fontStyle(/* Italic */1),
        /* :: */[
          Css.marginLeft(Css.em(0.5)),
          /* :: */[
            Css.opacity(0.5),
            /* [] */0
          ]
        ]
      ]
    ]);

var right = Css.style(/* :: */[
      Css.textAlign(/* Right */2),
      /* [] */0
    ]);

var updated = Css.style(/* :: */[
      Css.opacity(0.5),
      /* :: */[
        Css.fontSize(Css.em(0.85)),
        /* :: */[
          Css.unsafe("whiteSpace", "nowrap"),
          /* :: */[
            Css.opacity(0.75),
            /* [] */0
          ]
        ]
      ]
    ]);

var stars = Css.style(/* :: */[
      Css.opacity(0.5),
      /* :: */[
        Css.fontSize(Css.em(0.85)),
        /* :: */[
          Css.unsafe("whiteSpace", "nowrap"),
          /* :: */[
            Css.opacity(0.75),
            /* [] */0
          ]
        ]
      ]
    ]);

var starIcon = Css.style(/* :: */[
      Css.marginLeft(Css.em(0.25)),
      /* :: */[
        Css.transform(Css.translateY(Css.px(-1))),
        /* :: */[
          Css.unsafe("fill", Theme.Inverted[/* Color */0][/* text */1]),
          /* :: */[
            Css.opacity(0.5),
            /* [] */0
          ]
        ]
      ]
    ]);

var count = Css.style(/* :: */[
      Css.fontSize(Css.em(0.85)),
      /* :: */[
        Css.opacity(0.75),
        /* [] */0
      ]
    ]);

var ListItem = /* module */[
  /* root */root,
  /* name */name,
  /* version */version,
  /* right */right,
  /* updated */updated,
  /* stars */stars,
  /* starIcon */starIcon,
  /* count */count
];

var Index = /* module */[
  /* keywords */keywords,
  /* links */links,
  /* lists */lists,
  /* ListItem */ListItem
];

exports._reset  = _reset;
exports._global = _global;
exports.Index   = Index;
/*  Not a pure module */
