// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block  = require("bs-platform/lib/js/block.js");
var Glamor = require("bs-glamor/src/glamor.js");

require('./reset.css')
;

require('./global.css')
;

var keywords = Glamor.css(/* :: */[
      Glamor.textAlign("center"),
      /* :: */[
        Glamor.marginTop("3em"),
        /* :: */[
          Glamor.lineHeight("1.5em"),
          /* :: */[
            /* Selector */Block.__(1, [
                "& > a",
                /* :: */[
                  Glamor.display("inline-block"),
                  /* :: */[
                    Glamor.color("white"),
                    /* :: */[
                      Glamor.textDecoration("none"),
                      /* :: */[
                        Glamor.margin("0 1ex"),
                        /* :: */[
                          Glamor.whiteSpace("nowrap"),
                          /* :: */[
                            /* Selector */Block.__(1, [
                                "& > .count",
                                /* :: */[
                                  Glamor.color("rgba(255, 255, 255, 0.5)"),
                                  /* :: */[
                                    Glamor.marginLeft(".5ex"),
                                    /* [] */0
                                  ]
                                ]
                              ]),
                            /* :: */[
                              /* Selector */Block.__(1, [
                                  "&:hover > .label",
                                  /* :: */[
                                    Glamor.textDecoration("underline"),
                                    /* [] */0
                                  ]
                                ]),
                              /* [] */0
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]),
            /* [] */0
          ]
        ]
      ]
    ]);

var links = Glamor.css(/* :: */[
      Glamor.textAlign("center"),
      /* :: */[
        /* Selector */Block.__(1, [
            "& > a",
            /* :: */[
              Glamor.color("white"),
              /* :: */[
                Glamor.fontSize(".85rem"),
                /* :: */[
                  Glamor.textDecoration("none"),
                  /* :: */[
                    Glamor.margin("0 1em"),
                    /* :: */[
                      /* Selector */Block.__(1, [
                          "&:hover",
                          /* :: */[
                            Glamor.opacity(".75"),
                            /* [] */0
                          ]
                        ]),
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]
          ]),
        /* [] */0
      ]
    ]);

var lists = Glamor.css(/* :: */[
      Glamor.display("flex"),
      /* :: */[
        Glamor.justifyContent("space-around"),
        /* :: */[
          Glamor.marginTop("3em"),
          /* :: */[
            /* Selector */Block.__(1, [
                "& > *",
                /* :: */[
                  Glamor.padding("0 1em"),
                  /* :: */[
                    Glamor.width("40%"),
                    /* :: */[
                      Glamor.minWidth("300px"),
                      /* :: */[
                        /* Selector */Block.__(1, [
                            "& > h2",
                            /* :: */[
                              Glamor.color("white"),
                              /* :: */[
                                Glamor.textAlign("center"),
                                /* :: */[
                                  Glamor.fontSize("1.1em"),
                                  /* :: */[
                                    Glamor.fontWeight("600"),
                                    /* :: */[
                                      Glamor.margin(".5em 0"),
                                      /* :: */[
                                        Glamor.textTransform("lowercase"),
                                        /* :: */[
                                          Glamor.fontVariant("small-caps"),
                                          /* :: */[
                                            Glamor.paddingBottom(".5em"),
                                            /* :: */[
                                              Glamor.borderBottom("1px solid rgba(255, 255, 255, .5)"),
                                              /* [] */0
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]),
                        /* :: */[
                          /* Selector */Block.__(1, [
                              "& > div",
                              /* :: */[
                                Glamor.background("none"),
                                /* :: */[
                                  Glamor.border("none"),
                                  /* :: */[
                                    Glamor.padding("0"),
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ]),
                          /* [] */0
                        ]
                      ]
                    ]
                  ]
                ]
              ]),
            /* [] */0
          ]
        ]
      ]
    ]);

var root = Glamor.css(/* :: */[
      Glamor.display("flex"),
      /* :: */[
        Glamor.justifyContent("space-between"),
        /* :: */[
          Glamor.marginBottom(".5em"),
          /* [] */0
        ]
      ]
    ]);

var name = Glamor.css(/* :: */[
      Glamor.color("white"),
      /* :: */[
        Glamor.textDecoration("none"),
        /* :: */[
          /* Selector */Block.__(1, [
              "&:hover",
              /* :: */[
                Glamor.textDecoration("underline"),
                /* [] */0
              ]
            ]),
          /* [] */0
        ]
      ]
    ]);

var version = Glamor.css(/* :: */[
      Glamor.fontSize(".85em"),
      /* :: */[
        Glamor.fontStyle("italic"),
        /* :: */[
          Glamor.marginLeft(".5em"),
          /* :: */[
            Glamor.color("white"),
            /* :: */[
              Glamor.opacity(".5"),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var right = Glamor.css(/* :: */[
      Glamor.textAlign("right"),
      /* [] */0
    ]);

var updated = Glamor.css(/* :: */[
      Glamor.opacity(".5"),
      /* :: */[
        Glamor.fontSize(".85em"),
        /* :: */[
          Glamor.whiteSpace("nowrap"),
          /* :: */[
            Glamor.color("white"),
            /* :: */[
              Glamor.opacity(".75"),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var stars = Glamor.css(/* :: */[
      Glamor.opacity(".5"),
      /* :: */[
        Glamor.fontSize(".85em"),
        /* :: */[
          Glamor.whiteSpace("nowrap"),
          /* :: */[
            Glamor.color("white"),
            /* :: */[
              Glamor.opacity(".75"),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var starIcon = Glamor.css(/* :: */[
      Glamor.marginLeft(".25em"),
      /* :: */[
        Glamor.transform("translateY(-1px)"),
        /* :: */[
          Glamor.fill("white"),
          /* :: */[
            Glamor.opacity(".5"),
            /* [] */0
          ]
        ]
      ]
    ]);

var count = Glamor.css(/* :: */[
      Glamor.opacity(".5"),
      /* :: */[
        Glamor.fontSize(".85em"),
        /* :: */[
          Glamor.color("white"),
          /* :: */[
            Glamor.opacity(".75"),
            /* [] */0
          ]
        ]
      ]
    ]);

var ListItem = /* module */[
  /* root */root,
  /* name */name,
  /* version */version,
  /* right */right,
  /* updated */updated,
  /* stars */stars,
  /* starIcon */starIcon,
  /* count */count
];

var Index = /* module */[
  /* keywords */keywords,
  /* links */links,
  /* lists */lists,
  /* ListItem */ListItem
];

exports.Index = Index;
/*  Not a pure module */
