// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Link        = require("../../bindings/gatsby/link.js");
var $$Array     = require("bs-platform/lib/js/array.js");
var React       = require("react");
var Styles      = require("../styles/Styles.js");
var Control     = require("../components/helpers/Control.js");
var Helpers     = require("../utils/Helpers.js");
var TopList     = require("../components/TopList.js");
var SearchBox   = require("../components/SearchBox.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Index");

function make(data, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", undefined, ReasonReact.element(/* None */0, /* None */0, SearchBox.make(/* array */[])), React.createElement("div", {
                      className: Styles.Index[/* keywords */0]
                    }, ReasonReact.element(/* None */0, /* None */0, Control.$$Map[/* make */1]($$Array.map((function (edge) {
                                    return edge.node;
                                  }), data.keywords.edges), (function (keyword) {
                                return ReasonReact.element(/* None */0, /* None */0, Link.make(keyword.slug, /* None */0, /* None */0, /* array */[
                                                React.createElement("span", {
                                                      className: "label"
                                                    }, Helpers.text(keyword.name)),
                                                React.createElement("span", {
                                                      className: "count"
                                                    }, Helpers.text(keyword.count))
                                              ]));
                              })))), React.createElement("div", {
                      className: Styles.Index[/* lists */2]
                    }, React.createElement("div", undefined, React.createElement("h2", undefined, Helpers.text("Recent releases")), ReasonReact.element(/* None */0, /* None */0, TopList.make($$Array.map((function (edge) {
                                        return edge.node;
                                      }), data.recentPackages.edges), /* updated */500154939, /* array */[]))), React.createElement("div", undefined, React.createElement("h2", undefined, Helpers.text("Most popular")), ReasonReact.element(/* None */0, /* None */0, TopList.make($$Array.map((function (edge) {
                                        return edge.node;
                                      }), data.popularPackages.edges), /* stars */67859553, /* array */[])))));
    });
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.data, /* array */[]);
      }));


  export const query = graphql`
    query IndexQuery {
      recentPackages: allPackages(filter: { type: { eq: "published" } }, limit: 10, sort: { fields: [updated], order: DESC } ) {
        edges {
          node {
            ...package
          }
        }
      }

      popularPackages: allPackages(limit: 10, sort: { fields: [popularity], order: DESC } ) {
        edges {
          node {
            ...package
          }
        }
      }

      keywords: allKeywords(sort: { fields: [count], order: DESC } ) {
        edges {
          node {
            name
            count
            slug
          }
        }
      }
    }

    fragment package on Packages {
      name
      version
      description
      keywords
      license
      updated
      stars
      slug
    }
  `

;

exports.component = component;
exports.make      = make;
exports.$$default = $$default;
exports.default   = $$default;
exports.__esModule= true;
/* component Not a pure module */
