// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array        = require("bs-platform/lib/js/array.js");
var React          = require("react");
var ReasonReact    = require("reason-react/src/ReasonReact.js");
var PackageSummary = require("../components/PackageSummary.js");

var component = ReasonReact.statelessComponent("Packages");

function make(data, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", undefined, $$Array.map((function ($$package) {
                        return ReasonReact.element(/* None */0, /* None */0, PackageSummary.make($$package, /* array */[]));
                      }), $$Array.map((function (edge) {
                            return edge.node;
                          }), data.allPackagesJson.edges)));
    });
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.data, /* array */[]);
      }));


  export const query = graphql`
    query IndexQuery {
      allPackagesJson {
        edges {
          node {
            name
            version
            description
            keywords
            license
            updated
            stars

            fields {
              slug
            }
          }
        }
      }
    }
  `

;

exports.component = component;
exports.make      = make;
exports.$$default = $$default;
exports.default   = $$default;
exports.__esModule= true;
/* component Not a pure module */
