// Generated by BUCKLESCRIPT VERSION 1.9.0, PLEASE EDIT WITH CARE
'use strict';

var Link        = require("../../bindings/gatsby/link.js");
var React       = require("react");
var ReasonReact = require("reason-react/src/reasonReact.js");

function text(prim) {
  return prim;
}

var component = ReasonReact.statelessComponent("Page 2");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", undefined, React.createElement("h1", undefined, "Hi from the second page"), React.createElement("p", undefined, "Welcome to page 2"), ReasonReact.element(/* None */0, /* None */0, Link.make("/", /* None */0, /* array */["Go back to the homepage"])));
    });
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, (function () {
        return make(/* array */[]);
      }));

exports.text      = text;
exports.component = component;
exports.make      = make;
exports.$$default = $$default;
exports.default   = $$default;
/* component Not a pure module */
