// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Css   = require("bs-css/src/Css.js");
var Theme = require("../styles/Theme.js");

function flag(style_, invert) {
  return Css.style(/* :: */[
              Css.display(/* InlineBlock */11),
              /* :: */[
                Css.opacity(0.75),
                /* :: */[
                  Css.fontSize(Css.em(0.75)),
                  /* :: */[
                    Css.lineHeight(Css.em(1.6)),
                    /* :: */[
                      Css.marginRight(Css.em(1)),
                      /* :: */[
                        Css.unsafe("whiteSpace", "nowrap"),
                        /* :: */[
                          Css.unsafe("padding", "0 1ex"),
                          /* :: */[
                            style_ >= 937841383 ? Css.backgroundColor(invert ? Css.white : Theme.Color[/* primary */0]) : Css.border(Css.px(1), /* Solid */2, invert ? Css.white : Theme.Color[/* primary */0]),
                            /* :: */[
                              Css.color(style_ >= 937841383 ? (
                                      invert ? Theme.Color[/* primary */0] : Css.white
                                    ) : (
                                      invert ? Css.white : Theme.Color[/* primary */0]
                                    )),
                              /* :: */[
                                Css.borderRadius(Css.ex(0.5)),
                                /* [] */0
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

var flags = Css.style(/* [] */0);

exports.flag  = flag;
exports.flags = flags;
/* flags Not a pure module */
