// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry       = require("bs-platform/lib/js/curry.js");
var React       = require("react");
var Vrroom      = require("vrroom/src/Vrroom.bs.js");
var FlagsStyles = require("./FlagsStyles.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Flag");

function make(label, style, invert, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("span", {
                  className: FlagsStyles.flag(style, invert)
                }, Vrroom.Helpers[/* text */0](label));
    });
  return newrecord;
}

var Flag = /* module */[
  /* component */component,
  /* make */make
];

var component$1 = ReasonReact.statelessComponent("Flags");

function make$1($$package, $staropt$star, _) {
  var invert = $staropt$star ? $staropt$star[0] : /* false */0;
  var newrecord = component$1.slice();
  newrecord[/* render */9] = (function () {
      var match = +($$package.type === "unpublished");
      return React.createElement("span", {
                  className: "flags" + FlagsStyles.flags
                }, match !== 0 ? ReasonReact.element(/* None */0, /* None */0, make("unpublished", /* Black */-937474657, invert, /* array */[])) : Vrroom.Helpers[/* null */1], ReasonReact.element(/* None */0, /* None */0, Curry._3(Vrroom.Control[/* Map */0][/* make */1], $$package.flags, /* None */0, (function (flag) {
                            return ReasonReact.element(/* Some */[flag], /* None */0, make(flag, /* Heavy */937841383, invert, /* array */[]));
                          }))));
    });
  return newrecord;
}

var Control = 0;

var Styles = 0;

exports.Control   = Control;
exports.Styles    = Styles;
exports.Flag      = Flag;
exports.component = component$1;
exports.make      = make$1;
/* component Not a pure module */
