// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Css   = require("bs-css/src/Css.js");
var Theme = require("../styles/Theme.js");

function root(context) {
  return Css.style(/* :: */[
              Css.backgroundColor(context >= 431720585 ? Theme.Color[/* darkPrimary */1] : Theme.Color[/* darkBackground */3]),
              /* :: */[
                Css.unsafe("marginTop", "auto"),
                /* :: */[
                  Css.selector("& > div", /* :: */[
                        Css.display(/* Flex */3),
                        /* :: */[
                          Css.padding(Css.em(1.45)),
                          /* :: */[
                            Css.paddingTop(Css.em(1)),
                            /* :: */[
                              Css.selector("& > section", /* :: */[
                                    Css.opacity(0.65),
                                    /* :: */[
                                      Css.transition(/* None */0, /* Some */[500], /* None */0, "opacity"),
                                      /* :: */[
                                        Css.width(Css.pct(20)),
                                        /* :: */[
                                          Css.selector("&:last-child", /* :: */[
                                                Css.opacity(0.75),
                                                /* :: */[
                                                  Css.unsafe("marginLeft", "auto"),
                                                  /* :: */[
                                                    Css.alignSelf(/* FlexEnd */1),
                                                    /* :: */[
                                                      Css.textAlign(/* Right */2),
                                                      /* [] */0
                                                    ]
                                                  ]
                                                ]
                                              ]),
                                          /* :: */[
                                            Css.selector("&:hover", /* :: */[
                                                  Css.opacity(1),
                                                  /* [] */0
                                                ]),
                                            /* :: */[
                                              Css.selector("& h1", /* :: */[
                                                    Css.fontSize(Css.em(0.85)),
                                                    /* :: */[
                                                      Css.textTransform(/* Lowercase */2),
                                                      /* :: */[
                                                        Css.unsafe("fontVariant", "small-caps"),
                                                        /* :: */[
                                                          Css.opacity(0.5),
                                                          /* :: */[
                                                            Css.marginBottom(Css.em(0.35)),
                                                            /* [] */0
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ]),
                                              /* :: */[
                                                Css.selector("& a", /* :: */[
                                                      Css.textDecorationLine(/* None */0),
                                                      /* :: */[
                                                        Css.fontSize(Css.rem(0.85)),
                                                        /* :: */[
                                                          Css.opacity(0.75),
                                                          /* :: */[
                                                            Css.selector("&:hover", /* :: */[
                                                                  Css.opacity(1),
                                                                  /* [] */0
                                                                ]),
                                                            /* [] */0
                                                          ]
                                                        ]
                                                      ]
                                                    ]),
                                                /* [] */0
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]),
                              /* [] */0
                            ]
                          ]
                        ]
                      ]),
                  /* [] */0
                ]
              ]
            ]);
}

var algoliaLogo = Css.style(/* :: */[
      Css.height(Css.em(1)),
      /* :: */[
        Css.opacity(0.75),
        /* [] */0
      ]
    ]);

exports.root        = root;
exports.algoliaLogo = algoliaLogo;
/* algoliaLogo Not a pure module */
