// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Tag                  = require("./Tag.js");
var Link                 = require("../../bindings/gatsby/link.js");
var $$Array              = require("bs-platform/lib/js/array.js");
var React                = require("react");
var FaStar               = require("../vendor/icons/FaStar.js");
var FaTags               = require("../vendor/icons/FaTags.js");
var Helpers              = require("../utils/Helpers.js");
var TimeAgo              = require("../vendor/TimeAgo.js");
var ReasonReact          = require("reason-react/src/ReasonReact.js");
var PackageSummaryStyles = require("./PackageSummaryStyles.js");

var component = ReasonReact.statelessComponent("PackageSummary");

function make($$package, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: PackageSummaryStyles.root
                }, React.createElement("div", {
                      className: PackageSummaryStyles.left
                    }, ReasonReact.element(/* None */0, /* None */0, Link.make($$package.fields.slug, /* None */0, /* array */[Helpers.text($$package.name)])), Helpers.text(" (" + ($$package.version + ")")), React.createElement("div", undefined, Helpers.text($$package.description)), React.createElement("div", undefined, ReasonReact.element(/* None */0, /* None */0, FaTags.make(/* Some */["#ccc"], /* array */[])), $$Array.map((function (keyword) {
                                return ReasonReact.element(/* None */0, /* None */0, Tag.make(keyword, /* array */[]));
                              }), $$package.keywords))), React.createElement("div", {
                      className: PackageSummaryStyles.right
                    }, React.createElement("div", {
                          className: PackageSummaryStyles.updated
                        }, ReasonReact.element(/* None */0, /* None */0, TimeAgo.make($$package.updated, /* array */[]))), React.createElement("div", {
                          className: PackageSummaryStyles.license
                        }, Helpers.text($$package.license)), React.createElement("div", {
                          className: PackageSummaryStyles.stars
                        }, Helpers.text($$package.stars), ReasonReact.element(/* None */0, /* None */0, FaStar.make(/* Some */[PackageSummaryStyles.starIcon], /* None */0, /* array */[])))));
    });
  return newrecord;
}

var Styles = 0;

exports.Styles    = Styles;
exports.component = component;
exports.make      = make;
/* component Not a pure module */
