// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Control        = require("./helpers/Control.js");
var ReasonReact    = require("reason-react/src/ReasonReact.js");
var PackageSummary = require("./PackageSummary.js");

var component = ReasonReact.statelessComponent("PackageList");

function make(packages, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, Control.$$Map[/* make */1](packages, (function ($$package) {
                        return ReasonReact.element(/* Some */[$$package.id], /* None */0, PackageSummary.make($$package, /* array */[]));
                      })));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
