// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Glamor = require("bs-glamor/src/glamor.js");

var root = Glamor.css(/* :: */[
      Glamor.position("relative"),
      /* [] */0
    ]);

var input = Glamor.css(/* :: */[
      Glamor.display("block"),
      /* :: */[
        Glamor.background("white"),
        /* :: */[
          Glamor.border("1px solid #eee"),
          /* :: */[
            Glamor.padding(".25em .5em"),
            /* :: */[
              Glamor.width("50vw"),
              /* :: */[
                Glamor.margin("0 auto"),
                /* :: */[
                  Glamor.color("#666"),
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var results = Glamor.css(/* :: */[
      Glamor.position("absolute"),
      /* :: */[
        Glamor.zIndex("10"),
        /* :: */[
          Glamor.width("100%"),
          /* :: */[
            Glamor.boxShadow("1px 1px 0 1px rgba(0, 0, 0, .05)"),
            /* [] */0
          ]
        ]
      ]
    ]);

exports.root    = root;
exports.input   = input;
exports.results = results;
/* root Not a pure module */
