// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Tag                  = require("./Tag.js");
var Icon                 = require("../bindings/Icon.js");
var Link                 = require("../bindings/gatsby/link.js");
var Score                = require("./Score.js");
var React                = require("react");
var Control              = require("./helpers/Control.js");
var Helpers              = require("../utils/Helpers.js");
var TimeAgo              = require("../bindings/TimeAgo.js");
var ReasonReact          = require("reason-react/src/ReasonReact.js");
var PackageSummaryStyles = require("./PackageSummaryStyles.js");

var component = ReasonReact.statelessComponent("PackageSummary");

function make($$package, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var description = $$package.description;
      var tmp = description === "" ? Helpers.nbsp : Helpers.text(description);
      var match = $$package.stars;
      var match$1 = $$package.license;
      return React.createElement("div", {
                  className: PackageSummaryStyles.root($$package.type)
                }, React.createElement("div", undefined, ReasonReact.element(/* None */0, /* None */0, Link.make($$package.slug, /* Some */[PackageSummaryStyles.name], /* None */0, /* array */[Helpers.text($$package.name)])), React.createElement("span", {
                          className: PackageSummaryStyles.version
                        }, Helpers.text($$package.version)), React.createElement("span", {
                          className: PackageSummaryStyles.unpublishedLabel($$package.type)
                        }, Helpers.text("unpublished")), React.createElement("div", {
                          className: PackageSummaryStyles.description
                        }, tmp), React.createElement("div", {
                          className: PackageSummaryStyles.tags
                        }, ReasonReact.element(/* None */0, /* None */0, Icon.Tags[/* make */0](/* Some */[PackageSummaryStyles.tagsIcon], /* array */[])), ReasonReact.element(/* None */0, /* None */0, Control.$$Map[/* make */1]($$package.keywords, /* None */0, (function (keyword) {
                                    return ReasonReact.element(/* Some */[keyword], /* None */0, Tag.make(keyword, /* array */[]));
                                  }))))), React.createElement("div", {
                      className: PackageSummaryStyles.props
                    }, React.createElement("div", undefined, React.createElement("span", {
                              className: PackageSummaryStyles.stars
                            }, (match == null) ? Helpers.text("-") : Helpers.text(match), ReasonReact.element(/* None */0, /* None */0, Icon.Star[/* make */0](/* Some */[PackageSummaryStyles.starIcon], /* array */[]))), ReasonReact.element(/* None */0, /* None */0, Score.make($$package, /* array */[]))), React.createElement("div", {
                          className: PackageSummaryStyles.updated
                        }, ReasonReact.element(/* None */0, /* None */0, TimeAgo.make($$package.updated, /* array */[]))), (match$1 == null) ? React.createElement("div", {
                            className: PackageSummaryStyles.nolicense
                          }, Helpers.text("No license")) : React.createElement("div", {
                            className: PackageSummaryStyles.license
                          }, Helpers.text(match$1))));
    });
  return newrecord;
}

var Styles = 0;

exports.Styles    = Styles;
exports.component = component;
exports.make      = make;
/* component Not a pure module */
