// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block  = require("bs-platform/lib/js/block.js");
var Glamor = require("bs-glamor/src/glamor.js");

var root = Glamor.css(/* :: */[
      Glamor.display("flex"),
      /* :: */[
        Glamor.justifyContent("space-between"),
        /* :: */[
          Glamor.border("1px solid #eee"),
          /* :: */[
            Glamor.background("white"),
            /* :: */[
              Glamor.padding(".5em 1em"),
              /* :: */[
                /* Selector */Block.__(1, [
                    "& a",
                    /* :: */[
                      Glamor.color("#DD4C39"),
                      /* :: */[
                        Glamor.fontSize("1.1em"),
                        /* :: */[
                          Glamor.textDecoration("none"),
                          /* [] */0
                        ]
                      ]
                    ]
                  ]),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

var left = Glamor.css(/* [] */0);

var version = Glamor.css(/* :: */[
      Glamor.fontSize(".85em"),
      /* :: */[
        Glamor.fontStyle("italic"),
        /* :: */[
          Glamor.marginLeft(".5em"),
          /* [] */0
        ]
      ]
    ]);

var right = Glamor.css(/* :: */[
      Glamor.textAlign("right"),
      /* [] */0
    ]);

var updated = Glamor.css(/* :: */[
      Glamor.opacity(".5"),
      /* :: */[
        Glamor.fontSize(".85em"),
        /* :: */[
          Glamor.whiteSpace("nowrap"),
          /* [] */0
        ]
      ]
    ]);

var license = Glamor.css(/* :: */[
      Glamor.opacity(".5"),
      /* :: */[
        Glamor.fontSize(".85em"),
        /* :: */[
          Glamor.whiteSpace("nowrap"),
          /* [] */0
        ]
      ]
    ]);

var nolicense = Glamor.css(/* :: */[
      Glamor.color("red"),
      /* :: */[
        Glamor.fontSize(".85em"),
        /* :: */[
          Glamor.whiteSpace("nowrap"),
          /* [] */0
        ]
      ]
    ]);

var stars = Glamor.css(/* :: */[
      Glamor.opacity(".5"),
      /* :: */[
        Glamor.fontSize(".85em"),
        /* :: */[
          Glamor.whiteSpace("nowrap"),
          /* [] */0
        ]
      ]
    ]);

var starIcon = Glamor.css(/* :: */[
      Glamor.marginLeft(".25em"),
      /* :: */[
        Glamor.transform("translateY(-1px)"),
        /* [] */0
      ]
    ]);

exports.root      = root;
exports.left      = left;
exports.version   = version;
exports.right     = right;
exports.updated   = updated;
exports.license   = license;
exports.nolicense = nolicense;
exports.stars     = stars;
exports.starIcon  = starIcon;
/* root Not a pure module */
