// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array        = require("bs-platform/lib/js/array.js");
var React          = require("react");
var ReasonReact    = require("reason-react/src/ReasonReact.js");
var PackageSummary = require("./PackageSummary.js");

var component = ReasonReact.statelessComponent("PackageList");

function make(packages, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", undefined, $$Array.map((function ($$package) {
                        return ReasonReact.element(/* Some */[$$package.id], /* None */0, PackageSummary.make($$package, /* array */[]));
                      }), packages));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
