// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block      = require("bs-platform/lib/js/block.js");
var Colors     = require("../styles/Colors.js");
var Glamor     = require("bs-glamor/src/glamor.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

var root_000 = Glamor.display("flex");

var root_001 = /* :: */[
  Glamor.justifyContent("space-between"),
  /* :: */[
    Glamor.padding(".5em 1em"),
    /* :: */[
      Glamor.marginBottom(".5em"),
      /* :: */[
        Glamor.boxShadow(Colors.Shadow[/* panel */1]),
        /* :: */[
          /* Selector */Block.__(1, [
              "& a",
              /* :: */[
                Glamor.color(Colors.link),
                /* :: */[
                  Glamor.fontSize("1.1em"),
                  /* :: */[
                    Glamor.textDecoration("none"),
                    /* [] */0
                  ]
                ]
              ]
            ]),
          /* [] */0
        ]
      ]
    ]
  ]
];

var root = /* :: */[
  root_000,
  root_001
];

var published = Glamor.css(Pervasives.$at(root, /* :: */[
          Glamor.background(Colors.Panel[/* background */0]),
          /* [] */0
        ]));

var unpublished = Glamor.css(Pervasives.$at(root, /* :: */[
          Glamor.background(Colors.Panel[/* crosshatchBackground */1]),
          /* [] */0
        ]));

var left = Glamor.css(/* [] */0);

var version = Glamor.css(/* :: */[
      Glamor.fontSize(".85em"),
      /* :: */[
        Glamor.fontStyle("italic"),
        /* :: */[
          Glamor.marginLeft(".5em"),
          /* [] */0
        ]
      ]
    ]);

var unpublishedLabel = Glamor.css(/* :: */[
      Glamor.fontSize(".85em"),
      /* :: */[
        Glamor.fontStyle("italic"),
        /* :: */[
          Glamor.marginLeft(".5em"),
          /* :: */[
            Glamor.color(Colors.bad),
            /* [] */0
          ]
        ]
      ]
    ]);

var description = Glamor.css(/* :: */[
      Glamor.textOverflow("ellipsis"),
      /* :: */[
        Glamor.overflow("hidden"),
        /* [] */0
      ]
    ]);

var tagsIcon = Glamor.css(/* :: */[
      Glamor.opacity(".25"),
      /* [] */0
    ]);

var right = Glamor.css(/* :: */[
      Glamor.textAlign("right"),
      /* [] */0
    ]);

var updated = Glamor.css(/* :: */[
      Glamor.opacity(".5"),
      /* :: */[
        Glamor.fontSize(".85em"),
        /* :: */[
          Glamor.whiteSpace("nowrap"),
          /* [] */0
        ]
      ]
    ]);

var license = Glamor.css(/* :: */[
      Glamor.opacity(".5"),
      /* :: */[
        Glamor.fontSize(".85em"),
        /* :: */[
          Glamor.whiteSpace("nowrap"),
          /* [] */0
        ]
      ]
    ]);

var nolicense = Glamor.css(/* :: */[
      Glamor.color(Colors.bad),
      /* :: */[
        Glamor.fontSize(".85em"),
        /* :: */[
          Glamor.whiteSpace("nowrap"),
          /* [] */0
        ]
      ]
    ]);

var stars = Glamor.css(/* :: */[
      Glamor.opacity(".5"),
      /* :: */[
        Glamor.fontSize(".85em"),
        /* :: */[
          Glamor.whiteSpace("nowrap"),
          /* [] */0
        ]
      ]
    ]);

var starIcon = Glamor.css(/* :: */[
      Glamor.marginLeft(".25em"),
      /* :: */[
        Glamor.transform("translateY(-1px)"),
        /* :: */[
          Glamor.opacity(".5"),
          /* [] */0
        ]
      ]
    ]);

exports.root             = root;
exports.published        = published;
exports.unpublished      = unpublished;
exports.left             = left;
exports.version          = version;
exports.unpublishedLabel = unpublishedLabel;
exports.description      = description;
exports.tagsIcon         = tagsIcon;
exports.right            = right;
exports.updated          = updated;
exports.license          = license;
exports.nolicense        = nolicense;
exports.stars            = stars;
exports.starIcon         = starIcon;
/* root Not a pure module */
