// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Link = require("../bindings/gatsby/link.js");
var Vrroom = require("vrroom/src/Vrroom.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var TypedGlamor = require("typed-glamor/src/TypedGlamor.bs.js");

var style = TypedGlamor.css(/* None */0, /* :: */[
      TypedGlamor.display(TypedGlamor.inlineBlock),
      /* :: */[
        TypedGlamor.opacity(0.75),
        /* :: */[
          TypedGlamor.fontSize(TypedGlamor.em(0.75)),
          /* :: */[
            TypedGlamor.lineHeight(TypedGlamor.em(1.6)),
            /* :: */[
              TypedGlamor.marginLeft(TypedGlamor.em(0.5)),
              /* :: */[
                TypedGlamor.whiteSpace(TypedGlamor.nowrap),
                /* :: */[
                  TypedGlamor.backgroundColor(TypedGlamor.hex("fff3")),
                  /* :: */[
                    TypedGlamor.padding2(TypedGlamor.zero, TypedGlamor.ex(1)),
                    /* :: */[
                      TypedGlamor.textDecoration(TypedGlamor.none),
                      /* :: */[
                        TypedGlamor.borderRadius(TypedGlamor.ex(0.5)),
                        /* :: */[
                          TypedGlamor.hover(/* :: */[
                                TypedGlamor.opacity(1),
                                /* :: */[
                                  TypedGlamor.textDecoration(TypedGlamor.underline),
                                  /* [] */0
                                ]
                              ]),
                          /* [] */0
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var component = ReasonReact.statelessComponent("Tag");

function make(name, url, $staropt$star, _) {
  var customStyle = $staropt$star ? $staropt$star[0] : "";
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, Link.make(url, /* Some */[TypedGlamor.toString(style) + (" " + customStyle)], /* None */0, /* array */[Vrroom.text(name)]));
    });
  return newrecord;
}

var Tag = /* module */[
  /* style */style,
  /* component */component,
  /* make */make
];

var component$1 = ReasonReact.statelessComponent("Tag");

function make$1(name, _) {
  var newrecord = component$1.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, make(name, "/keyword/" + name, /* None */0, /* array */[]));
    });
  return newrecord;
}

var Keyword = /* module */[
  /* component */component$1,
  /* make */make$1
];

var customStyle = TypedGlamor.css(/* None */0, /* :: */[
      TypedGlamor.border3(TypedGlamor.px(1), TypedGlamor.solid, TypedGlamor.currentColor),
      /* [] */0
    ]);

var component$2 = ReasonReact.statelessComponent("Tag");

function make$2(name, _) {
  var newrecord = component$2.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, make(name, "/category/" + name, /* Some */[TypedGlamor.toString(customStyle)], /* array */[]));
    });
  return newrecord;
}

var Category = /* module */[
  /* customStyle */customStyle,
  /* component */component$2,
  /* make */make$2
];

exports.Tag = Tag;
exports.Keyword = Keyword;
exports.Category = Category;
/* style Not a pure module */
