// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Icon          = require("../bindings/Icon.js");
var Link          = require("../bindings/gatsby/link.js");
var React         = require("react");
var Control       = require("./helpers/Control.js");
var Helpers       = require("../utils/Helpers.js");
var TimeAgo       = require("../bindings/TimeAgo.js");
var ReasonReact   = require("reason-react/src/ReasonReact.js");
var Js_primitive  = require("bs-platform/lib/js/js_primitive.js");
var TopListStyles = require("./TopListStyles.js");

var component = ReasonReact.statelessComponent("TopList");

function make(packages, value, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, Control.$$Map[/* make */1](packages, /* None */0, (function ($$package) {
                        return React.createElement("div", {
                                    key: $$package.name,
                                    className: TopListStyles.root
                                  }, React.createElement("div", undefined, ReasonReact.element(/* None */0, /* None */0, Link.make($$package.slug, /* Some */[TopListStyles.name], /* None */0, /* array */[Helpers.text($$package.name)])), React.createElement("span", {
                                            className: TopListStyles.version
                                          }, Helpers.text($$package.version))), React.createElement("div", undefined, value >= 500154939 ? React.createElement("div", {
                                              className: TopListStyles.updated
                                            }, ReasonReact.element(/* None */0, /* None */0, TimeAgo.make($$package.updated, /* array */[]))) : ReasonReact.element(/* None */0, /* None */0, Control.IfSome[/* make */1](Js_primitive.null_undefined_to_opt($$package.stars), (function (stars) {
                                                    return React.createElement("div", {
                                                                className: TopListStyles.stars
                                                              }, Helpers.text(stars), ReasonReact.element(/* None */0, /* None */0, Icon.Star[/* make */0](/* Some */[TopListStyles.starIcon], /* array */[])));
                                                  })))));
                      })));
    });
  return newrecord;
}

var Styles = 0;

exports.Styles    = Styles;
exports.component = component;
exports.make      = make;
/* component Not a pure module */
