// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var Theme = require("../styles/Theme.js");

var root = Css.style(/* :: */[
      Css.display(/* Flex */3),
      /* :: */[
        Css.justifyContent(/* SpaceBetween */5),
        /* :: */[
          Css.marginBottom(Css.em(0.5)),
          /* [] */0
        ]
      ]
    ]);

var name = Css.style(/* :: */[
      Css.textDecorationLine(/* None */0),
      /* :: */[
        Css.hover(/* :: */[
              Css.textDecorationLine(/* Values */[/* :: */[
                      /* Underline */0,
                      /* [] */0
                    ]]),
              /* [] */0
            ]),
        /* [] */0
      ]
    ]);

var version = Css.style(/* :: */[
      Css.fontSize(Css.em(0.85)),
      /* :: */[
        Css.fontStyle(/* Italic */1),
        /* :: */[
          Css.marginLeft(Css.em(0.5)),
          /* :: */[
            Css.opacity(0.5),
            /* [] */0
          ]
        ]
      ]
    ]);

var updated = Css.style(/* :: */[
      Css.opacity(0.5),
      /* :: */[
        Css.fontSize(Css.em(0.85)),
        /* :: */[
          Css.unsafe("whiteSpace", "nowrap"),
          /* :: */[
            Css.opacity(0.75),
            /* [] */0
          ]
        ]
      ]
    ]);

var stars = Css.style(/* :: */[
      Css.opacity(0.5),
      /* :: */[
        Css.fontSize(Css.em(0.85)),
        /* :: */[
          Css.unsafe("whiteSpace", "nowrap"),
          /* :: */[
            Css.opacity(0.75),
            /* [] */0
          ]
        ]
      ]
    ]);

var starIcon = Css.style(/* :: */[
      Css.marginLeft(Css.em(0.25)),
      /* :: */[
        Css.transform(Css.translateY(Css.px(-1))),
        /* :: */[
          Css.unsafe("fill", Theme.Inverted[/* Color */0][/* text */1]),
          /* :: */[
            Css.opacity(0.5),
            /* [] */0
          ]
        ]
      ]
    ]);

exports.root = root;
exports.name = name;
exports.version = version;
exports.updated = updated;
exports.stars = stars;
exports.starIcon = starIcon;
/* root Not a pure module */
