// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");

function root(isPublished) {
  return Css.style(/* :: */[
              Css.fontSize(Css.em(0.85)),
              /* :: */[
                Css.fontStyle(/* Italic */1),
                /* :: */[
                  Css.marginLeft(Css.em(0.5)),
                  /* :: */[
                    Css.selector("> div", isPublished ? /* [] */0 : /* :: */[
                            Css.textDecorationLine(/* Values */[/* :: */[
                                    /* LineThrough */2,
                                    /* [] */0
                                  ]]),
                            /* [] */0
                          ]),
                    /* [] */0
                  ]
                ]
              ]
            ]);
}

var tooltip = Css.style(/* :: */[
      Css.backgroundColor(Css.white),
      /* :: */[
        Css.boxShadow(Css.shadow(/* Some */[1], /* Some */[1], /* Some */[3], /* Some */[1], Css.rgba(0, 0, 0, 0.1))),
        /* :: */[
          Css.unsafe("padding", ".5em 1em"),
          /* :: */[
            Css.selector("& div", /* :: */[
                  Css.unsafe("whiteSpace", "nowrap"),
                  /* [] */0
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

exports.root = root;
exports.tooltip = tooltip;
/* tooltip Not a pure module */
