// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function text(prim) {
  return prim;
}

var nbsp = ('\u00a0');

exports.text = text;
exports.nbsp = nbsp;
/* nbsp Not a pure module */
