// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Link                  = require("../../bindings/gatsby/link.js");
var Curry                 = require("bs-platform/lib/js/curry.js");
var React                 = require("react");
var Helmet                = require("../../bindings/gatsby/helmet.js");
var Helpers               = require("../utils/Helpers.js");
var ReasonReact           = require("reason-react/src/ReasonReact.js");
var FrontPageLayoutStyles = require("./FrontPageLayoutStyles.js");

var component = ReasonReact.statelessComponent("FrontPageLayout");

function make(children, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: FrontPageLayoutStyles.root
                }, React.createElement("div", {
                      className: FrontPageLayoutStyles.links
                    }, ReasonReact.element(/* None */0, /* None */0, Link.make("/packages", /* None */0, /* None */0, /* array */[Helpers.text("Packages")])), ReasonReact.element(/* None */0, /* None */0, Link.make("/keywords", /* None */0, /* None */0, /* array */[Helpers.text("Keywords")])), ReasonReact.element(/* None */0, /* None */0, Link.make("/packages/unpublished", /* None */0, /* None */0, /* array */[Helpers.text("Unpublished")]))), ReasonReact.element(/* None */0, /* None */0, Helmet.make(/* Some */["REDEX"], /* None */0, /* array */[])), React.createElement("div", {
                      className: FrontPageLayoutStyles.header
                    }, React.createElement("div", {
                          className: FrontPageLayoutStyles.widthContainer
                        }, React.createElement("h1", {
                              className: FrontPageLayoutStyles.title
                            }, React.createElement("svg", {
                                  className: FrontPageLayoutStyles.logo,
                                  viewBox: "0 0 24 24"
                                }, React.createElement("path", {
                                      d: "M19,2L14,6.5V17.5L19,13V2M6.5,5C4.55,5 2.45,5.4 1,6.5V21.16C1,21.41 1.25,21.66 1.5,21.66C1.6,21.66 1.65,21.59 1.75,21.59C3.1,20.94 5.05,20.5 6.5,20.5C8.45,20.5 10.55,20.9 12,22C13.35,21.15 15.8,20.5 17.5,20.5C19.15,20.5 20.85,20.81 22.25,21.56C22.35,21.61 22.4,21.59 22.5,21.59C22.75,21.59 23,21.34 23,21.09V6.5C22.4,6.05 21.75,5.75 21,5.5V7.5L21,13V19C19.9,18.65 18.7,18.5 17.5,18.5C15.8,18.5 13.35,19.15 12,20V13L12,8.5V6.5C10.55,5.4 8.45,5 6.5,5V5Z"
                                    })), Helpers.text("redex")))), React.createElement("div", {
                      className: FrontPageLayoutStyles.widthContainer
                    }, Curry._1(children, /* () */0)), React.createElement("div", {
                      className: FrontPageLayoutStyles.footer
                    }, React.createElement("div", {
                          className: FrontPageLayoutStyles.widthContainer
                        }, React.createElement("section", undefined, React.createElement("h1", undefined, Helpers.text("Project")), React.createElement("ul", undefined, React.createElement("li", undefined, React.createElement("a", {
                                          href: "https://github.com/rebench/rebench.github.io"
                                        }, Helpers.text("Source Code Repository"))), React.createElement("li", undefined, React.createElement("a", {
                                          href: "https://github.com/rebench/rebench.github.io/issues"
                                        }, Helpers.text("Support / Bug Tracker"))))), React.createElement("section", undefined, React.createElement("h1", undefined, Helpers.text("Made with")), React.createElement("ul", undefined, React.createElement("li", undefined, React.createElement("a", {
                                          href: "https://www.gatsbyjs.org/"
                                        }, Helpers.text("Gatsby"))), React.createElement("li", undefined, React.createElement("a", {
                                          href: "https://reasonml.github.io/reason-react/"
                                        }, Helpers.text("ReasonReact"))), React.createElement("li", undefined, React.createElement("a", {
                                          href: "https://github.com/bucklescript/bucklescript"
                                        }, Helpers.text("BuckleScript"))), React.createElement("li", undefined, React.createElement("a", {
                                          href: "https://github.com/threepointone/glamor"
                                        }, Helpers.text("glamor"))))), React.createElement("section", undefined, React.createElement("h1", undefined, Helpers.text("Reason")), React.createElement("ul", undefined, React.createElement("li", undefined, React.createElement("a", {
                                          href: "https://reasonml.github.io/"
                                        }, Helpers.text("Reason Homepage"))), React.createElement("li", undefined, React.createElement("a", {
                                          href: "https://reasonml.github.io/guide"
                                        }, Helpers.text("Reason Guide"))), React.createElement("li", undefined, React.createElement("a", {
                                          href: "https://reasonml.github.io/try"
                                        }, Helpers.text("Reason Playground"))))), React.createElement("section", undefined, React.createElement("img", {
                                  className: FrontPageLayoutStyles.algoliaLogo,
                                  src: "search-by-algolia-white.svg"
                                })))));
    });
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.children, /* array */[]);
      }));

var Styles = 0;

var $$__esModule = /* true */1;

exports.Styles       = Styles;
exports.component    = component;
exports.make         = make;
exports.$$default    = $$default;
exports.default      = $$default;
exports.__esModule   = true;
exports.$$__esModule = $$__esModule;
/* component Not a pure module */
