// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block  = require("bs-platform/lib/js/block.js");
var Colors = require("../styles/Colors.js");
var Glamor = require("bs-glamor/src/glamor.js");

var root = Glamor.css(/* :: */[
      Glamor.display("flex"),
      /* :: */[
        Glamor.flexDirection("column"),
        /* :: */[
          Glamor.background(Colors.Inverted[/* background */0]),
          /* :: */[
            Glamor.minHeight("100vh"),
            /* :: */[
              Glamor.color(Colors.Inverted[/* text */1]),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var header = Glamor.css(/* [] */0);

var links = Glamor.css(/* :: */[
      Glamor.textAlign("center"),
      /* :: */[
        Glamor.paddingTop(".5em"),
        /* :: */[
          /* Selector */Block.__(1, [
              "& > a",
              /* :: */[
                Glamor.fontVariant("small-caps"),
                /* :: */[
                  Glamor.textDecoration("none"),
                  /* :: */[
                    Glamor.textTransform("lowercase"),
                    /* :: */[
                      Glamor.margin("0 1em"),
                      /* :: */[
                        Glamor.opacity(".75"),
                        /* :: */[
                          /* Selector */Block.__(1, [
                              "&:hover",
                              /* :: */[
                                Glamor.opacity("1"),
                                /* [] */0
                              ]
                            ]),
                          /* [] */0
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]),
          /* [] */0
        ]
      ]
    ]);

var inactiveLink = Glamor.css(/* :: */[
      Glamor.opacity(".25 !important"),
      /* :: */[
        Glamor.cursor("default"),
        /* [] */0
      ]
    ]);

var widthContainer = Glamor.css(/* :: */[
      Glamor.margin("0 auto"),
      /* :: */[
        Glamor.maxWidth("960px"),
        /* :: */[
          Glamor.padding("1.0875rem 1.45rem"),
          /* [] */0
        ]
      ]
    ]);

var title = Glamor.css(/* :: */[
      Glamor.margin("1em 0 0"),
      /* :: */[
        Glamor.textAlign("center"),
        /* :: */[
          Glamor.fontVariant("small-caps"),
          /* :: */[
            Glamor.fontSize("2.5rem"),
            /* :: */[
              Glamor.lineHeight("1.1"),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var logo = Glamor.css(/* :: */[
      Glamor.display("block"),
      /* :: */[
        Glamor.margin("0 auto"),
        /* :: */[
          Glamor.height("3em"),
          /* :: */[
            Glamor.fill(Colors.Inverted[/* text */1]),
            /* [] */0
          ]
        ]
      ]
    ]);

var footer = Glamor.css(/* :: */[
      Glamor.background(Colors.darkPrimary),
      /* :: */[
        Glamor.marginTop("auto"),
        /* :: */[
          /* Selector */Block.__(1, [
              "& > div",
              /* :: */[
                Glamor.display("flex"),
                /* :: */[
                  /* Selector */Block.__(1, [
                      "& > section",
                      /* :: */[
                        Glamor.opacity(".65"),
                        /* :: */[
                          Glamor.transition("opacity .5s"),
                          /* :: */[
                            Glamor.width("20%"),
                            /* :: */[
                              /* Selector */Block.__(1, [
                                  "&:last-child",
                                  /* :: */[
                                    Glamor.opacity(".75"),
                                    /* :: */[
                                      Glamor.marginLeft("auto"),
                                      /* :: */[
                                        Glamor.alignSelf("end"),
                                        /* :: */[
                                          Glamor.textAlign("right"),
                                          /* [] */0
                                        ]
                                      ]
                                    ]
                                  ]
                                ]),
                              /* :: */[
                                /* Selector */Block.__(1, [
                                    "&:hover",
                                    /* :: */[
                                      Glamor.opacity("1"),
                                      /* [] */0
                                    ]
                                  ]),
                                /* :: */[
                                  /* Selector */Block.__(1, [
                                      "& h1",
                                      /* :: */[
                                        Glamor.fontSize(".85em"),
                                        /* :: */[
                                          Glamor.textTransform("lowercase"),
                                          /* :: */[
                                            Glamor.fontVariant("small-caps"),
                                            /* :: */[
                                              Glamor.opacity(".5"),
                                              /* :: */[
                                                Glamor.marginBottom(".35em"),
                                                /* [] */0
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]),
                                  /* :: */[
                                    /* Selector */Block.__(1, [
                                        "& a",
                                        /* :: */[
                                          Glamor.textDecoration("none"),
                                          /* :: */[
                                            Glamor.fontSize(".85rem"),
                                            /* :: */[
                                              Glamor.opacity(".75"),
                                              /* :: */[
                                                /* Selector */Block.__(1, [
                                                    "&:hover",
                                                    /* :: */[
                                                      Glamor.opacity("1"),
                                                      /* [] */0
                                                    ]
                                                  ]),
                                                /* [] */0
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]),
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]),
                  /* [] */0
                ]
              ]
            ]),
          /* [] */0
        ]
      ]
    ]);

var algoliaLogo = Glamor.css(/* :: */[
      Glamor.height("1em"),
      /* :: */[
        Glamor.opacity(".75"),
        /* [] */0
      ]
    ]);

exports.root           = root;
exports.header         = header;
exports.links          = links;
exports.inactiveLink   = inactiveLink;
exports.widthContainer = widthContainer;
exports.title          = title;
exports.logo           = logo;
exports.footer         = footer;
exports.algoliaLogo    = algoliaLogo;
/* root Not a pure module */
