// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block  = require("bs-platform/lib/js/block.js");
var Glamor = require("bs-glamor/src/glamor.js");

var root = Glamor.css(/* :: */[
      Glamor.display("flex"),
      /* :: */[
        Glamor.flexDirection("column"),
        /* :: */[
          Glamor.background("#dd4c39"),
          /* :: */[
            Glamor.minHeight("100vh"),
            /* [] */0
          ]
        ]
      ]
    ]);

var header = Glamor.css(/* [] */0);

var links = Glamor.css(/* :: */[
      Glamor.textAlign("center"),
      /* :: */[
        Glamor.paddingTop(".5em"),
        /* :: */[
          /* Selector */Block.__(1, [
              "& > a",
              /* :: */[
                Glamor.color("white"),
                /* :: */[
                  Glamor.fontVariant("small-caps"),
                  /* :: */[
                    Glamor.textDecoration("none"),
                    /* :: */[
                      Glamor.textTransform("lowercase"),
                      /* :: */[
                        Glamor.margin("0 1em"),
                        /* :: */[
                          Glamor.opacity(".75"),
                          /* :: */[
                            /* Selector */Block.__(1, [
                                "&:hover",
                                /* :: */[
                                  Glamor.opacity("1"),
                                  /* [] */0
                                ]
                              ]),
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]),
          /* [] */0
        ]
      ]
    ]);

var widthContainer = Glamor.css(/* :: */[
      Glamor.margin("0 auto"),
      /* :: */[
        Glamor.maxWidth("960px"),
        /* :: */[
          Glamor.padding("1.0875rem 1.45rem"),
          /* [] */0
        ]
      ]
    ]);

var title = Glamor.css(/* :: */[
      Glamor.margin("1em 0 0"),
      /* :: */[
        Glamor.textAlign("center"),
        /* :: */[
          Glamor.fontVariant("small-caps"),
          /* :: */[
            Glamor.color("white"),
            /* :: */[
              Glamor.fontSize("2.5rem"),
              /* :: */[
                Glamor.lineHeight("1.1"),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

var logo = Glamor.css(/* :: */[
      Glamor.display("block"),
      /* :: */[
        Glamor.margin("0 auto"),
        /* :: */[
          Glamor.height("3em"),
          /* :: */[
            Glamor.fill("white"),
            /* [] */0
          ]
        ]
      ]
    ]);

var footer = Glamor.css(/* :: */[
      Glamor.background("rgba(0, 0, 0, 0.25)"),
      /* :: */[
        Glamor.marginTop("auto"),
        /* :: */[
          /* Selector */Block.__(1, [
              "& > div",
              /* :: */[
                Glamor.display("flex"),
                /* :: */[
                  /* Selector */Block.__(1, [
                      "& > section",
                      /* :: */[
                        Glamor.opacity(".5"),
                        /* :: */[
                          Glamor.transition("opacity .5s"),
                          /* :: */[
                            Glamor.width("20%"),
                            /* :: */[
                              /* Selector */Block.__(1, [
                                  "&:last-child",
                                  /* :: */[
                                    Glamor.opacity(".75"),
                                    /* :: */[
                                      Glamor.marginLeft("auto"),
                                      /* :: */[
                                        Glamor.alignSelf("end"),
                                        /* [] */0
                                      ]
                                    ]
                                  ]
                                ]),
                              /* :: */[
                                /* Selector */Block.__(1, [
                                    "&:hover",
                                    /* :: */[
                                      Glamor.opacity("1"),
                                      /* [] */0
                                    ]
                                  ]),
                                /* :: */[
                                  /* Selector */Block.__(1, [
                                      "& h1",
                                      /* :: */[
                                        Glamor.fontSize(".85em"),
                                        /* :: */[
                                          Glamor.color("rgba(255, 255, 255, .65)"),
                                          /* :: */[
                                            Glamor.textTransform("lowercase"),
                                            /* :: */[
                                              Glamor.fontVariant("small-caps"),
                                              /* :: */[
                                                Glamor.marginBottom(".35em"),
                                                /* [] */0
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]),
                                  /* :: */[
                                    /* Selector */Block.__(1, [
                                        "& a",
                                        /* :: */[
                                          Glamor.color("white"),
                                          /* :: */[
                                            Glamor.textDecoration("none"),
                                            /* :: */[
                                              Glamor.fontSize(".85rem"),
                                              /* :: */[
                                                /* Selector */Block.__(1, [
                                                    "&:hover",
                                                    /* :: */[
                                                      Glamor.color("white"),
                                                      /* [] */0
                                                    ]
                                                  ]),
                                                /* [] */0
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]),
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]),
                  /* [] */0
                ]
              ]
            ]),
          /* [] */0
        ]
      ]
    ]);

var algoliaLogo = Glamor.css(/* :: */[
      Glamor.height("1em"),
      /* [] */0
    ]);

exports.root           = root;
exports.header         = header;
exports.links          = links;
exports.widthContainer = widthContainer;
exports.title          = title;
exports.logo           = logo;
exports.footer         = footer;
exports.algoliaLogo    = algoliaLogo;
/* root Not a pure module */
