// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block  = require("bs-platform/lib/js/block.js");
var Colors = require("../styles/Colors.js");
var Glamor = require("bs-glamor/src/glamor.js");

var root = Glamor.css(/* [] */0);

var header = Glamor.css(/* [] */0);

var widthContainer = Glamor.css(/* :: */[
      Glamor.margin("0 auto"),
      /* :: */[
        Glamor.maxWidth("960px"),
        /* :: */[
          Glamor.padding("1.0875rem 1.45rem"),
          /* [] */0
        ]
      ]
    ]);

var title = Glamor.css(/* :: */[
      Glamor.margin("0"),
      /* :: */[
        /* Selector */Block.__(1, [
            "& > a",
            /* :: */[
              Glamor.color(Colors.link),
              /* :: */[
                Glamor.textDecoration("none"),
                /* [] */0
              ]
            ]
          ]),
        /* [] */0
      ]
    ]);

exports.root           = root;
exports.header         = header;
exports.widthContainer = widthContainer;
exports.title          = title;
/* root Not a pure module */
