// Generated by BUCKLESCRIPT VERSION 1.9.0, PLEASE EDIT WITH CARE
'use strict';

var Link        = require("../../bindings/gatsby/link.js");
var Curry       = require("bs-platform/lib/js/curry.js");
var React       = require("react");
var Helmet      = require("../../bindings/gatsby/helmet.js");
var ReasonReact = require("reason-react/src/reasonReact.js");

function text(prim) {
  return prim;
}

((require('./index.css')));

var component = ReasonReact.statelessComponent("IndexLayout Header");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  style: {
                    background: "rebeccapurple",
                    marginBottom: "1.45rem"
                  }
                }, React.createElement("div", {
                      style: {
                        margin: "0 auto",
                        maxWidth: "960px",
                        padding: "1.45rem 1.0875rem"
                      }
                    }, React.createElement("h1", {
                          style: {
                            margin: "0"
                          }
                        }, ReasonReact.element(/* None */0, /* None */0, Link.make("/", /* Some */[{
                                    color: "white",
                                    textDecoration: "none"
                                  }], /* array */["Gatsby"])))));
    });
  return newrecord;
}

var Header = /* module */[
  /* component */component,
  /* make */make
];

var component$1 = ReasonReact.statelessComponent("IndexLayout");

function make$1(children, _) {
  var newrecord = component$1.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", undefined, ReasonReact.element(/* None */0, /* None */0, Helmet.make(/* Some */["Gatsby Default Starter"], /* Some */[/* array */[
                            {
                              name: "description",
                              content: "Sample"
                            },
                            {
                              name: "keywords",
                              content: "sample, something"
                            }
                          ]], /* array */[])), ReasonReact.element(/* None */0, /* None */0, make(/* array */[])), React.createElement("div", {
                      style: {
                        margin: "0 auto",
                        maxWidth: "960px",
                        padding: "0px 1.0875rem 1.45rem",
                        paddingTop: "0"
                      }
                    }, Curry._1(children, /* () */0)));
    });
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component$1, (function (jsProps) {
        return make$1(jsProps.children, /* array */[]);
      }));

var __esModule = /* true */1;

exports.text       = text;
exports.Header     = Header;
exports.component  = component$1;
exports.make       = make$1;
exports.$$default  = $$default;
exports.default    = $$default;
exports.__esModule = __esModule;
/*  Not a pure module */
